package land.melon.lab.entityhider

import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

data class Config(
    @Expose
    @SerializedName("sightTracerThreadsAmount")
    val sightTracerThreadsAmount: Int = Runtime.getRuntime().availableProcessors(),
    @Expose
    @SerializedName("maxViewDistance")
    val maxViewDistance: Int = 64,
    @Expose
    @SerializedName("frontViewAngle")
    val frontViewAngle: Double = 90.0,
    @Expose
    @SerializedName("backViewAngle")
    val backViewAngle: Double = 90.0,
    @Expose
    @SerializedName("pitchViewAngle")
    val pitchViewAngle: Double = 90.0,
    @Expose
    @SerializedName("ignorePassableBlocks")
    val ignorePassableBlocks: Boolean = true,
    @Expose
    @SerializedName("ignoreLiquidBlocks")
    val ignoreLiquidBlocks: Boolean = true,
    @Expose
    @SerializedName("ignoreBlocks")
    val ignoreBlocks: List<String> = mutableListOf(
        "LECTERN",
        "HOPPER",
        "DAYLIGHT_DETECTOR",
        "CHEST",
        "FARMLAND",
        "CHORUS_PLANT",
        "CHORUS_FLOWER",
        "CHAIN",
        "IRON_BARS",
        "CACTUS",
        "ENCHANTING_TABLE",
        "END_PORTAL_FRAME",
        "ANVIL",
        "CHIPPED_ANVIL",
        "DAMAGED_ANVIL",
        "SLIME_BLOCK",
        "SCAFFOLDING",
        "FLOWER_POT",
        "SKELETON_HEAD",
        "WITHER_SKELETON_HEAD",
        "PLAYER_HEAD",
        "ZOMBIE_HEAD",
        "CREEPER_HEAD",
        "DRAGON_HEAD",

        "TRAPPED_CHEST",
        "OAK_LEAVES",
        "SPRUCE_LEAVES",
        "BIRCH_LEAVES",
        "JUNGLE_LEAVES",
        "ACACIA_LEAVES",
        "DARK_OAK_LEAVES",
        "IRON_DOOR",
        "OAK_DOOR",
        "SPRUCE_DOOR",
        "BIRTH_DOOR",
        "JUNGLE_DOOR",
        "ACACIA_DOOR",
        "DARK_OAK_DOOR",
        "CRIMSON_DOOR",
        "WARPED_DOOR",
        "IRON_TRAPDOOR",
        "OAK_TRAPDOOR",
        "SPRUCE_TRAPDOOR",
        "BIRTH_TRAPDOOR",
        "JUNGLE_TRAPDOOR",
        "ACACIA_TRAPDOOR",
        "DARK_OAK_TRAPDOOR",
        "CRIMSON_TRAPDOOR",
        "WARPED_TRAPDOOR",
        "OAK_FENCE_GATE",
        "SPRUCE_FENCE_GATE",
        "BIRTH_FENCE_GATE",
        "JUNGLE_FENCE_GATE",
        "ACACIA_FENCE_GATE",
        "DARK_OAK_FENCE_GATE",
        "CRIMSON_FENCE_GATE",
        "WARPED_FENCE_GATE",
        "NETHER_BRICK_FENCE",
        "OAK_FENCE",
        "SPRUCE_FENCE",
        "BIRTH_FENCE",
        "JUNGLE_FENCE",
        "ACACIA_FENCE",
        "DARK_OAK_FENCE",
        "CRIMSON_FENCE",
        "WARPED_FENCE",
        "WHITE_BED",
        "ORANGE_BED",
        "MAGENTA_BED",
        "LIGHT_BLUE_BED",
        "YELLOW_BED",
        "LIME_BED",
        "PINK_BED",
        "GRAY_BED",
        "LIGHT_GRAY_BED",
        "CYAN_BED",
        "PURPLE_BED",
        "BLUE_BED",
        "BROWN_BED",
        "GREEN_BED",
        "RED_BED",
        "BLACK_BED",
        "GLASS",
        "GLASS_PANE",
        "TINTED_GLASS",
        "WHITE_STAINED_GLASS",
        "ORANGE_STAINED_GLASS",
        "MAGENTA_STAINED_GLASS",
        "LIGHT_BLUE_STAINED_GLASS",
        "YELLOW_STAINED_GLASS",
        "LIME_STAINED_GLASS",
        "PINK_STAINED_GLASS",
        "GRAY_STAINED_GLASS",
        "LIGHT_GRAY_STAINED_GLASS",
        "CYAN_STAINED_GLASS",
        "PURPLE_STAINED_GLASS",
        "BLUE_STAINED_GLASS",
        "BROWN_STAINED_GLASS",
        "GREEN_STAINED_GLASS",
        "RED_STAINED_GLASS",
        "BLACK_STAINED_GLASS",
        "WHITE_STAINED_GLASS_PANE",
        "ORANGE_STAINED_GLASS_PANE",
        "MAGENTA_STAINED_GLASS_PANE",
        "LIGHT_BLUE_STAINED_GLASS_PANE",
        "YELLOW_STAINED_GLASS_PANE",
        "LIME_STAINED_GLASS_PANE",
        "PINK_STAINED_GLASS_PANE",
        "GRAY_STAINED_GLASS_PANE",
        "LIGHT_GRAY_STAINED_GLASS_PANE",
        "CYAN_STAINED_GLASS_PANE",
        "PURPLE_STAINED_GLASS_PANE",
        "BLUE_STAINED_GLASS_PANE",
        "BROWN_STAINED_GLASS_PANE",
        "GREEN_STAINED_GLASS_PANE",
        "RED_STAINED_GLASS_PANE",
        "BLACK_STAINED_GLASS_PANE"
    )

)
